name: ferrotienda_flutter_proyecto
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  mobile_scanner: ^7.2.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  permission_handler: ^12.0.1
  fl_chart: ^1.2.0
  print_bluetooth_thermal: ^1.1.9
  esc_pos_utils_plus: ^2.0.4
  image: ^4.8.0
  qr_flutter: ^4.1.0
  qr: ^3.0.2
  shared_preferences: ^2.5.5
  local_auth: ^3.0.1
  flutter_secure_storage: ^10.3.1
  table_calendar: ^3.2.0
  pdf: ^3.13.0
  path_provider: ^2.1.6
  share_plus: ^13.2.1
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.0  # 🔥 NUEVA DEPENDENCIA AÑADIDA PARA EL RPA
  flutter_barcode_scanner: ^2.0.0
  signature: ^5.4.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wyner_logo.png

# 🔥 AQUÍ ESTÁ LA SOLUCIÓN PARA EL ESCÁNER
dependency_overrides:
  flutter_barcode_scanner:
    git:
      url: https://github.com/decodevM/flutter_barcode_scanner.git
      ref: flutter-3.29